language: php
php:
- 5.5
- 5.6
- 7.0
before_script:
- echo \{\"http-basic\":\{\"repo.magento.com\":\{\"username\":\"${REPO_MAGENTO_PUBLIC}\",\"password\":\"${REPO_MAGENTO_PRIVATE}\"\}\},\"github-oauth\":\{\"github.com\":\"${GITHUB_TOKEN}\"\}\} > ~/.composer/auth.json
- composer install
script:
- vendor/bin/phing -verbose
after_script:
- vendor/bin/coveralls -v